FROM jenkins/jenkins:lts

USER root

# Install Docker CLI only (not daemon)
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/docker

USER jenkins
